version: "3.9"
services:
  greenflux:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
    - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Any_password123"
      ACCEPT_EULA: "Y"
